modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://www.github.com/xfacthd/buddingcrystals"
license="LGPL v2.1"

[[mods]]
    modId="buddingcrystals"
    version="${mod_version}"
    displayName="BuddingCrystals"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/buddingcrystals"
    logoFile="logo.png"
    authors="XFactHD"
    description='''
    '''

[[dependencies.buddingcrystals]]
    modId="neoforge"
    mandatory=true
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.buddingcrystals]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.buddingcrystals]]
    modId="dynamic_asset_generator"
    mandatory=true
    versionRange="[5.0.0,)"
    ordering="AFTER"
    side="CLIENT"
